services:
  n8n:
    image: ${GONKAGATE_IMAGE}:${GONKAGATE_IMAGE_TAG}
    restart: unless-stopped
    ports:
      - '${N8N_PORT}:5678'
    environment:
      GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
      TZ: ${TZ}
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
